export enum EServerErrors {
  NOT_FOUND = 404,
  SERVER_ERROR = 500,
  UNAUTHORIZED = 401,
  BAD_REQUEST = 400,
  FORBIDDEN = 403,
  CONFLICT = 409,
  METHOD_NOT_ALLOWED = 405,
  PARSING_ERROR = 'PARSING_ERROR',
}
